app/apps/shipment/urls.py
from django.urls import path

from .views import ShipmentCreateView, ShipmentUpdateView, ShipmentListView, ShipmentDeleteView, ShipmentSentView

app_name = 'shipment'

urlpatterns = [
    path('create/', ShipmentCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ShipmentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ShipmentDeleteView.as_view(), name='delete'),
    path('list/', ShipmentListView.as_view(), name='list'),
    path('sent/<int:pk>/', ShipmentSentView.as_view(), name='sent'),
]

app/shopping_cart/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.base.views import IndexView, UserView, LoginView, SettingsView
from apps.order.views import OrderDetail
from django.conf import settings
from django.conf.urls.static import static
import os

from .routers import urlpatterns as urlpatterns_routers


urlpatterns = [
    path('', IndexView.as_view(), name="home"),
    path(r'api/v1/', include(urlpatterns_routers)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/signup/', UserView.as_view(), name="signup"),
    path('shopping_cart/', OrderDetail.as_view(), name="index"),
    path('product/', include('apps.product.urls')),
    path('order/', include('apps.order.urls')),
    path('shipment/', include('apps.shipment.urls')),
    path('payment/', include('apps.payment.urls')),
    path('settings/', SettingsView.as_view(), name="settings"),
]


if os.environ.get("DEBUG"):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/apps/shipment/models.py
from django.db import models

from apps.order.models import Order

class Shipment(models.Model):
    STATUS_SHIPMENT_CHOICES = (
        ('new', 'Nuevo',),
        ('sent', 'Enviado',),
        ('delivered', 'Entregado',),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Pedido')
    address = models.CharField(max_length=255, null=True, blank=False, verbose_name='Dirección')
    status = models.CharField(max_length=50, default=STATUS_SHIPMENT_CHOICES[0][0], choices=STATUS_SHIPMENT_CHOICES, verbose_name='Estatus')

    def __str__(self):
        return "Envío #{}".format(self.id)

app/apps/shipment/forms.py
from django import forms
from .models import Shipment


class ShipmentForm(forms.ModelForm):
    class Meta:
        model = Shipment
        fields = ['order', 'address']

app/apps/shipment/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.shortcuts import redirect


from apps.base.decorators import is_client
from apps.base.utils import sent_email

from .forms import ShipmentForm
from .models  import Shipment

@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class ShipmentCreateView(CreateView):
    form_class = ShipmentForm
    model = Shipment
    success_url = reverse_lazy('shipment:list')


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class ShipmentUpdateView(UpdateView):
    form_class = ShipmentForm
    model = Shipment
    success_url = reverse_lazy('shipment:list')


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class ShipmentDeleteView(DeleteView):
    form_class = ShipmentForm
    model = Shipment
    success_url = reverse_lazy('shipment:list')


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class ShipmentListView(ListView):
    model = Shipment


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class ShipmentSentView(TemplateView):
    template_name = "shipment/sent.html"

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy("shipment:list")

    def get(self, *args, **kwargs):
        pk = kwargs.get('pk')

        shipment = Shipment.objects.filter(id=pk).first()
        if shipment is not None:
            shipment.status = 'sent'
            shipment.save()

            subject = "{} ha sido enviado".format(str(shipment.order))
            content = "El pedido ya se encuentra enviado, por favor estar atento."

            if shipment.order.created_by.email:
                sent_email(subject, shipment.order.created_by.email, content)

        return redirect(self.get_success_url())

app/apps/shipment/templates/shipment/shipment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-12 text-center">
        <form action="{% url 'shipment:delete' object.id %}" method="post">
            {% csrf_token %}
            <p>¿Está seguro que desea borrar "{{ object }}"?</p>
            <div class="modal-footer">
                <button type="submit" class="btn btn-danger">
                    Borrar
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/apps/shipment/templates/shipment/shipment_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row mt-5 ml-4">
            <div class="col-2 mb-3">
                {{ form.order.label }}:
            </div>
            <div class="col-9 mb-3">
                {{ form.order }}
            </div>
            <div class="col-2 mb-3">
                {{ form.address.label }}:
            </div>
            <div class="col-9 mb-3">
                {{ form.address }}
            </div>
        </div>
        <div class="row ml-4 mt-4">
            <div class="col-12">
                <div class="row">
                    <div class="col-6 text-left">
                        <a type="button" class="btn btn-secondary" href="{% url 'shipment:list' %}">Back</a>
                    </div>
                    <div class="col-6 text-right">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

app/apps/shipment/templates/shipment/shipment_list.html
{% extends 'base.html' %}
{% load base_filters %}

{% block content %}
    <div class="row">
        <div class="col-12 text-right mb-2">
            <a href="{% url 'shipment:create' %}"><i class="fa fa-plus"></i> Crear Envío</a>
        </div>
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Pedido
                        </th>
                        <th>
                            Estado
                        </th>
                        <th>
                            Dirección
                        </th>
                        <th class="text-center">
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>
                                {{ object.order }}
                            </td>
                            <td>
                                {{ object.get_status_display }}
                            </td>
                            <td>
                                {{ object.address }}
                            </td>
                            <td class="text-center">
                                <a href="{% url 'shipment:update' object.id %}"><i class="fa fa-edit"></i></a>
                                <a href="{% url 'shipment:delete' object.id %}"><i class="fa fa-trash"></i></a>
                                {% if object.status == 'new' %}
                                    <a href="{% url 'shipment:sent' object.id %}">Enviar pedido</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}