app/apps/product/urls.py
from django.urls import path

from .views import ProductCreateView, ProductUpdateView, ProductListView, ProductDeleteView

app_name = 'product'

urlpatterns = [
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('list/', ProductListView.as_view(), name='list'),
]

app/shopping_cart/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.base.views import IndexView, UserView, LoginView, SettingsView
from apps.order.views import OrderDetail
from django.conf import settings
from django.conf.urls.static import static
import os

from .routers import urlpatterns as urlpatterns_routers


urlpatterns = [
    path('', IndexView.as_view(), name="home"),
    path(r'api/v1/', include(urlpatterns_routers)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/signup/', UserView.as_view(), name="signup"),
    path('shopping_cart/', OrderDetail.as_view(), name="index"),
    path('product/', include('apps.product.urls')),
    path('order/', include('apps.order.urls')),
    path('shipment/', include('apps.shipment.urls')),
    path('payment/', include('apps.payment.urls')),
    path('settings/', SettingsView.as_view(), name="settings"),
]


if os.environ.get("DEBUG"):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/apps/product/models.py
from django.db import models
from django.core.exceptions import ValidationError


def validate_file_extension(value):
    ext_valid = ('jpg', 'jpeg', 'png')
    str_ext_valid = ' , '.join(ext_valid)
    if not value.name.endswith(ext_valid):
        raise ValidationError(u'%(value)s: Bat extension, only %(ext_valid)s',
                                params={'value': value, 'ext_valid': str_ext_valid})


class Product(models.Model):
    name = models.CharField(max_length=50, null=True, blank=False, verbose_name="Nombre")
    price = models.FloatField(default=0, null=False, blank=False, verbose_name="Precio")
    image = models.FileField(blank=True, null=True, verbose_name="Imagen", validators=[validate_file_extension])

    def __str__(self):
        return self.name

app/apps/product/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

app/apps/product/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required


from apps.base.decorators import is_client

from .forms import ProductForm
from .models  import Product

@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class ProductCreateView(CreateView):
    form_class = ProductForm
    model = Product
    success_url = reverse_lazy('product:list')


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class ProductUpdateView(UpdateView):
    form_class = ProductForm
    model = Product
    success_url = reverse_lazy('product:list')


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class ProductDeleteView(DeleteView):
    form_class = ProductForm
    model = Product
    success_url = reverse_lazy('product:list')


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class ProductListView(ListView):
    model = Product

app/apps/product/templates/product/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-12 text-center">
        <form action="{% url 'product:delete' object.id %}" method="post">
            {% csrf_token %}
            <p>¿Está seguro que desea borrar "{{ object }}"?</p>
            <div class="modal-footer">
                <button type="submit" class="btn btn-danger">
                    Borrar
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/apps/product/templates/product/product_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row mt-5 ml-4">
            <div class="col-2 mb-3">
                {{ form.name.label }}:
            </div>
            <div class="col-9 mb-3">
                {{ form.name }}
            </div>
            <div class="col-2 mb-3">
                {{ form.price.label }}:
            </div>
            <div class="col-9 mb-3">
                {{ form.price }}
            </div>
            <div class="col-2 mb-3">
                {{ form.image.label }}:
            </div>
            <div class="col-9 mb-3">
                {{ form.image }}
            </div>
        </div>
        <div class="row ml-4 mt-4">
            <div class="col-12">
                <div class="row">
                    <div class="col-6 text-left">
                        <a type="button" class="btn btn-secondary" href="{% url 'product:list' %}">Back</a>
                    </div>
                    <div class="col-6 text-right">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

app/apps/product/templates/product/product_list.html
{% extends 'base.html' %}
{% load base_filters %}

{% block content %}
    <div class="row">
        <div class="col-12 text-right mb-2">
            <a href="{% url 'product:create' %}"><i class="fa fa-plus"></i> Crear Producto</a>
        </div>
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Imagen
                        </th>
                        <th>
                            Nombre
                        </th>
                        <th>
                            Precio
                        </th>
                        <th class="text-center">
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>
                                <img class="custom-img" src="{{ object.image.url }}" alt="">
                            </td>
                            <td>
                                {{ object.name }}
                            </td>
                            <td>
                                {{ object.price|currency:'$' }}
                            </td>
                            <td class="text-center">
                                <a href="{% url 'product:update' object.id %}"><i class="fa fa-edit"></i></a>
                                <a href="{% url 'product:delete' object.id %}"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}