app/apps/order/urls.py
from django.urls import path

from .views import OrderCreateView, OrderUpdateView, OrderListView, OrderDeleteView

app_name = 'order'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='delete'),
    path('list/', OrderListView.as_view(), name='list'),
]

app/apps/product/urls.py
from django.urls import path

from .views import ProductCreateView, ProductUpdateView, ProductListView, ProductDeleteView

app_name = 'product'

urlpatterns = [
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('list/', ProductListView.as_view(), name='list'),
]

app/apps/shipment/urls.py
from django.urls import path

from .views import ShipmentCreateView, ShipmentUpdateView, ShipmentListView, ShipmentDeleteView, ShipmentSentView

app_name = 'shipment'

urlpatterns = [
    path('create/', ShipmentCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ShipmentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ShipmentDeleteView.as_view(), name='delete'),
    path('list/', ShipmentListView.as_view(), name='list'),
    path('sent/<int:pk>/', ShipmentSentView.as_view(), name='sent'),
]

app/shopping_cart/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.base.views import IndexView, UserView, LoginView, SettingsView
from apps.order.views import OrderDetail
from django.conf import settings
from django.conf.urls.static import static
import os

from .routers import urlpatterns as urlpatterns_routers


urlpatterns = [
    path('', IndexView.as_view(), name="home"),
    path(r'api/v1/', include(urlpatterns_routers)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/signup/', UserView.as_view(), name="signup"),
    path('shopping_cart/', OrderDetail.as_view(), name="index"),
    path('product/', include('apps.product.urls')),
    path('order/', include('apps.order.urls')),
    path('shipment/', include('apps.shipment.urls')),
    path('payment/', include('apps.payment.urls')),
    path('settings/', SettingsView.as_view(), name="settings"),
]


if os.environ.get("DEBUG"):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/apps/base/models.py
from django.db import models

# Create your models here.

app/apps/base/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView as CoreLoginView

from apps.base.decorators import is_client


@method_decorator(login_required, name='dispatch')
class IndexView(TemplateView):
    template_name = "index.html"


class UserView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'


class LoginView(CoreLoginView):
    form_class = AuthenticationForm

    def dispatch(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(self.get_success_url())

        return super().dispatch(*args, **kwargs)

    def get_success_url(self):

        if self.request.user.is_authenticated:
            if self.request.GET.get('next'):
                return self.request.GET.get('next')
            if self.request.user.is_superuser:
                return reverse_lazy('admin:index')
        return reverse_lazy('home')


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class SettingsView(TemplateView):
    template_name = "settings.html"

app/apps/base/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" ng-app="shopApp">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Shopping Car{% endblock %}</title>
    <script src="{% static 'base.js' %}" type="text/javascript"></script>

    <link rel="stylesheet" href="{% static 'bootstrap/4.1.3/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    <link href="{% static 'base.css' %}" rel="stylesheet">

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% block static %}{% endblock %}

</head>
<body>
    <div class="container">
        {% csrf_token %}
        <div class="row">
            <div class="col-1">
                <a href="{% url 'home' %}">Home</a>
            </div>
            <div style="min-height: 5rem;" class="row col-11">
                {% if request.user.is_authenticated %}
                    <div class="col-6 col-sm-6 col-xs-6">{{ request.user }}</div>
                    <div class="col-3 text-right">
                        <a href="{% url 'logout' %}">Logout</a>
                    </div>
                    <div class="col-1">
                        <span id="count_items" class="count-items d-none"></span>
                        <a href="{% url 'index' %}"><i class="fa fa-cart-arrow-down fa-2x"></i></a>
                    </div>
                    {% if request.user.is_superuser or request.user.is_staff %}
                    <div class="col-1">
                        <a href="{% url 'settings' %}"><i class="fa fa-cog fa-2x"></i></a>
                    </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
<footer>
    {% block footer %}{% endblock %}
</footer>
</html>

app/apps/base/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block static %}
    <script src="{% static 'index.js' %}" type="text/javascript"></script>
{% endblock %}


{% block content %}
    <div class="row mt-4" id="product-list">
    </div>
{% endblock %}

app/apps/base/templates/settings.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 mt-5">
            <div class="row">
                <div class="col-4">
                    <a href="{% url 'product:list' %}"><img class="settings_image" src="/media/product.png" alt=""></a>
                </div>
                <div class="col-4">
                    <a href="{% url 'order:list' %}"><img class="settings_image" src="/media/order.png" alt=""></a>
                </div>
                <div class="col-4">
                    <a href="{% url 'shipment:list' %}"><img class="settings_image" src="/media/shipment.png" alt=""></a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/apps/base/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign Up{% endblock %}

{% block content %}
<h2>Sign up</h2>
<form method="post" action="{% url 'signup' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock %}