app/apps/order/urls.py
from django.urls import path

from .views import OrderCreateView, OrderUpdateView, OrderListView, OrderDeleteView

app_name = 'order'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='create'),
    path('update/<int:pk>/', OrderUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', OrderDeleteView.as_view(), name='delete'),
    path('list/', OrderListView.as_view(), name='list'),
]

app/apps/product/urls.py
from django.urls import path

from .views import ProductCreateView, ProductUpdateView, ProductListView, ProductDeleteView

app_name = 'product'

urlpatterns = [
    path('create/', ProductCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('list/', ProductListView.as_view(), name='list'),
]

app/apps/shipment/urls.py
from django.urls import path

from .views import ShipmentCreateView, ShipmentUpdateView, ShipmentListView, ShipmentDeleteView, ShipmentSentView

app_name = 'shipment'

urlpatterns = [
    path('create/', ShipmentCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ShipmentUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ShipmentDeleteView.as_view(), name='delete'),
    path('list/', ShipmentListView.as_view(), name='list'),
    path('sent/<int:pk>/', ShipmentSentView.as_view(), name='sent'),
]

app/shopping_cart/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.base.views import IndexView, UserView, LoginView, SettingsView
from apps.order.views import OrderDetail
from django.conf import settings
from django.conf.urls.static import static
import os

from .routers import urlpatterns as urlpatterns_routers


urlpatterns = [
    path('', IndexView.as_view(), name="home"),
    path(r'api/v1/', include(urlpatterns_routers)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/signup/', UserView.as_view(), name="signup"),
    path('shopping_cart/', OrderDetail.as_view(), name="index"),
    path('product/', include('apps.product.urls')),
    path('order/', include('apps.order.urls')),
    path('shipment/', include('apps.shipment.urls')),
    path('payment/', include('apps.payment.urls')),
    path('settings/', SettingsView.as_view(), name="settings"),
]


if os.environ.get("DEBUG"):
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/apps/order/models.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    STATUS_CHOICES = (
        ('new', 'Nuevo',),
        ('confirmed', 'Confirmado',),
        ('paid', 'Pagado',),
        ('delivered', 'Entregado',),
    )
    total = models.FloatField(default=0, blank=True, null=True, verbose_name="Total")
    status = models.CharField(max_length=50, default=STATUS_CHOICES[0][0], choices=STATUS_CHOICES, verbose_name="Estatus")
    creation_date = models.DateTimeField(auto_now_add=True, null=True, verbose_name="Fecha de Creación")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, verbose_name="Creado Por")

    def items(self, request):
        items = []
        if self.item_set.exists():
            for item in self.item_set.all():
                image_path = None
                if item.product.image:
                    image_path = '{}://{}{}'.format(request.scheme, request.META.get('HTTP_HOST'), item.product.image.url)
                items.append(
                    {
                        'price': item.product.price if item.product is not None else 0,
                        'image_path': image_path,
                        'amount': item.amount,
                        'name': item.product.name if item.product is not None else '',
                        'id': item.id
                    }
                )

        return items

    def __str__(self):
        return "Pedido #{}".format(self.id)

app/apps/order/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['total']
        # realdonly = ['id', 'created_by', 'creation_date']

app/apps/order/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from apps.base.decorators import is_client

from .forms import OrderForm
from .models  import Order


@method_decorator(login_required, name='dispatch')
class OrderDetail(TemplateView):
    template_name = "order_detail.html"



@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class OrderCreateView(CreateView):
    form_class = OrderForm
    model = Order
    success_url = reverse_lazy('order:list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.created_by is None:
            self.object.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class OrderUpdateView(UpdateView):
    form_class = OrderForm
    model = Order
    success_url = reverse_lazy('order:list')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.created_by is None:
            self.object.created_by = self.request.user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class OrderDeleteView(DeleteView):
    form_class = OrderForm
    model = Order
    success_url = reverse_lazy('order:list')


@method_decorator(login_required, name='dispatch')
@method_decorator(is_client, name='dispatch')
class OrderListView(ListView):
    model = Order

app/apps/order/templates/order/order_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-12 text-center">
        <form action="{% url 'product:delete' object.id %}" method="post">
            {% csrf_token %}
            <p>¿Está seguro que desea borrar "{{ object }}"?</p>
            <div class="modal-footer">
                <button type="submit" class="btn btn-danger">
                    Borrar
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/apps/order/templates/order/order_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if object %}
        <div class="row">
            <div class="col-12 text-center">
                Pedido #{{object.id}}
            </div>
        </div>
        {% endif %}
        <div class="row mt-5 ml-4">
            <div class="col-2 mb-3">
                {{ form.total.label }}:
            </div>
            <div class="col-9 mb-3">
                {{ form.total }}
            </div>
        </div>
        <div class="row ml-4 mt-4">
            <div class="col-12">
                <div class="row">
                    <div class="col-6 text-left">
                        <a type="button" class="btn btn-secondary" href="{% url 'order:list' %}">Back</a>
                    </div>
                    <div class="col-6 text-right">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

app/apps/order/templates/order/order_list.html
{% extends 'base.html' %}
{% load base_filters %}

{% block content %}
    <div class="row">
        <div class="col-12 text-right mb-2">
            <a href="{% url 'order:create' %}"><i class="fa fa-plus"></i> Crear pedido</a>
        </div>
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Consecutivo
                        </th>
                        <th>
                            Creado Por
                        </th>
                        <th>
                            Estado
                        </th>
                        <th>
                            Total
                        </th>
                        <th class="text-center">
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td>
                                Pedido #{{ object.id }}
                            </td>
                            <td>
                                {{ object.created_by }}
                            </td>
                            <td>
                                {{ object.get_status_display }}
                            </td>
                            <td>
                                {{ object.total|default:0|currency:'$' }}
                            </td>
                            <td class="text-center">
                                <a href="{% url 'order:update' object.id %}"><i class="fa fa-edit"></i></a>
                                <a href="{% url 'order:delete' object.id %}"><i class="fa fa-trash"></i></a>
                                {% if object.status == 'paid' %}
                                    <a href="{% url 'shipment:create' %}">Procesar Envío</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}